### ISSUE TITLE
Expand the supported OS versions list

### ISSUE THREAD

**Issue by dfduarte** [target/network_interfaces_v2-cookbook#14]
Hello, just a note:

I've been testing this cookbook with a 2008 R2 server, and I saw that this cookbook works perfectly, if you update the Powershell to WMF 4.0. There is a cookbook (powershell) on supermarket, that do this job.

Maybe, this feature can be incorporated to the Cookbook, because the 2008 R2 is being discommissioned by MS, but a lot of companies use it yet.

(Just a suggestion, of course)

**Comment by jmccann** [comment]
This seems like it'd be something pretty simple to implement.  I personally don't have a need for it but if I were to receive a PR to do the above I'd gladly review/accept it.

Otherwise I could just add a note in the README.md concerning 2008R2 support and that it works, you just need to add the mentioned cookbook `powershell` to your run_list.

**Comment by dfduarte** [comment]
PR created

**Comment by jmccann** [comment]
Take care of by #15
